export const sample_foods = [
  {
    id: '1',
    name: 'Chicken Soup',
    cookTime: '40-50',
    price: 50,
    favorite: false,
    origins: ['India'],
    stars: 3.5,
    imageUrl: 'food-5.jpg',
    tags: ['Lunch'],
  },
  {
    id: '2',
    name: 'Set Dosa',
    price: 50,
    cookTime: '10-15',
    favorite: false,
    origins: ['India'],
    stars: 3,
    imageUrl: 'set-dosa.jpg',
    tags: ['Dosa'],
  },
  {
    id: '3',
    name: 'Masala Dosa',
    price: 60,
    cookTime: '15-20',
    favorite: false,
    origins: ['India'],
    stars: 3,
    imageUrl: 'masala dosa.jpg',
    tags: ['Dosa'],
  },
  {
    id: '4',
    name: 'Neer Dosa',
    price: 40,
    cookTime: '10-15',
    favorite: false,
    origins: ['India'],
    stars: 3,
    imageUrl: 'Neer dosa.jpg',
    tags: ['Dosa'],
  },
  {
    id: '5',
    name: 'Plain Dosa',
    price: 45,
    cookTime: '10-15',
    favorite: false,
    origins: ['india'],
    stars: 3,
    imageUrl: 'plain dosa.jpg',
    tags: ['Dosa'],
  },
  {
    id: '6',
    name: 'Ragi Dosa',
    price: 50,
    cookTime: '10-15',
    favorite: false,
    origins: ['India'],
    stars: 3,
    imageUrl: 'ragi dosa.jpg',
    tags: ['Dosa'],
  },
];

export const sample_tags = [
  { name: 'All', count: 14 },
  { name: 'Biriyani', count: 5 },
  { name: 'Dosa', count: 5 },
  { name: 'Idli', count: 3 },
  { name: 'Lunch', count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: 'Shakthi',
    email: 'shakthi@gmail.com',
    password: '123456',
    address: 'Bangarpet,Kolar',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'Yashwanth',
    email: 'yashwanth@gmail.com',
    password: '654321',
    address: 'Tekal,Malur,kolar',
    isAdmin: true,
  },
];
